name: kigali_price_check
description: A price comparison app for Rwanda.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6

  # Network & HTTP
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^4.0.2

  # Local Storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3

  # Utils
  intl: ^0.18.1
  get_it: ^7.6.4
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0

  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Charts
  fl_chart: ^0.63.0

  # Social Login
  google_sign_in: ^6.1.5

  # Phone Authentication
  country_code_picker: ^3.0.0

  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/screenshot/
    - .env
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
