// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLufeO5q-AWaomjWLMjn06fMX-cZBiJAc',
    appId: '1:55226443629:web:5a20f7ad855408acd91c64',
    messagingSenderId: '55226443629',
    projectId: 'kigalipricecheck',
    authDomain: 'kigalipricecheck.firebaseapp.com',
    storageBucket: 'kigalipricecheck.firebasestorage.app',
    measurementId: 'G-1G7P50RD7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLrqoZClkj_zrr1li7ZomOoKHwvIBCa8',
    appId: '1:55226443629:android:56f2b106c0de3fccd91c64',
    messagingSenderId: '55226443629',
    projectId: 'kigalipricecheck',
    storageBucket: 'kigalipricecheck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCN44ickMEcLNibuT03FBRqaQ2w05W9y0',
    appId: '1:55226443629:ios:eeeb32ff630fde45d91c64',
    messagingSenderId: '55226443629',
    projectId: 'kigalipricecheck',
    storageBucket: 'kigalipricecheck.firebasestorage.app',
    iosBundleId: 'com.example.priceComparisonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCN44ickMEcLNibuT03FBRqaQ2w05W9y0',
    appId: '1:55226443629:ios:eeeb32ff630fde45d91c64',
    messagingSenderId: '55226443629',
    projectId: 'kigalipricecheck',
    storageBucket: 'kigalipricecheck.firebasestorage.app',
    iosBundleId: 'com.example.priceComparisonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLufeO5q-AWaomjWLMjn06fMX-cZBiJAc',
    appId: '1:55226443629:web:45e9fd0def753d99d91c64',
    messagingSenderId: '55226443629',
    projectId: 'kigalipricecheck',
    authDomain: 'kigalipricecheck.firebaseapp.com',
    storageBucket: 'kigalipricecheck.firebasestorage.app',
    measurementId: 'G-K1QN25DM8K',
  );
}
